---
title: "HW4"
output: html_document
date: "2023-05-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(here)
library(tidyverse)
library(ggplot2)
library(janitor)
library(pracma)
```

```{r}
damage_data <- read.csv("damages.csv")
warming_data <- read.csv("warming.csv")
quad_dmg <- lm(damages~0 + warming+I(warming^2), damage_data)

ggplot(damage_data, aes(warming, damages)) + geom_point() + geom_jitter(width=.2) + stat_smooth(method = "lm", formula = y ~ x + I(x^2), size = 1) + ggtitle("Damages ($) Related to Global Mean Temperature Change (Celcius)") +labs(x="Warming (Celcius)", y="Damages ($)") + theme_minimal()
```

```{r}
base_warm <- tibble(warming=warming_data$warming_baseline)

predicted_baseline_dmg <- data.frame(predict_damage = predict(quad_dmg, newdata=tibble(warming=warming_data$warming_baseline))) %>%
                mutate(years=warming_data$year)

ggplot(predicted_baseline_dmg, aes(years, predict_damage)) + geom_point() + ggtitle("Predicted Damages Overtime Without Pulse")+ labs(x="Years", y="Predicted Damage")+theme_minimal()
```

```{r}
pulse_warm <- tibble(warming=warming_data$warming_pulse)
predicted_pulse_dmg <- data.frame(predict_damage = predict(quad_dmg, newdata=pulse_warm)) %>%
                mutate(years=warming_data$year)

ggplot(predicted_pulse_dmg, aes(years,predict_damage)) + geom_point() + ggtitle("Predicted Damages Overtime With Pulse")+ labs(x="Years", y="Predicted Damage")+theme_minimal()
```


```{r}
diff_damage <- cbind.data.frame(year=warming_data$year, diff=(predicted_pulse_dmg$predict_damage - predicted_baseline_dmg$predict_damage))

ggplot(diff_damage, aes(year, diff)) + geom_point() + labs(y="Difference between Baseline and Pulse", x="Years")+ggtitle("Difference in Damages Over Time that Arise from Pulse") + theme_minimal()
```


```{r}
diff_damage_per_ton <- cbind.data.frame(year=warming_data$year, diff_dmg=(predicted_pulse_dmg$predict_damage - predicted_baseline_dmg$predict_damage)/(35*10^9))

ggplot(diff_damage_per_ton, aes(year, diff_dmg)) + geom_point() + labs(y="Difference between Baseline and Pulse per Ton", x="Years") + ggtitle("Difference in Damages Over Time that Arise from Pulse per Ton CO2") + theme_minimal()
```

```{r}
df_dmgs = data.frame()
discount <- seq(.01,.08, .01)
years <- 2021:2100
for(i in 1:length(discount)){
for(j in 1:length(years)){
     future_discounted_dmg <- diff_damage_per_ton$diff_dmg * (1+discount[i])^years[j]
 }
   df_discount <- data.frame("rates" = discount[i], future_discounted_dmg)
   df_dmgs <- rbind(df_dmgs,df_discount)
}
 df_dmgs
 
# SCC_discounting <- df_dmgs %>% pivot_longer(tidyselect::everything(), names_to = "rates", values_to = "SCC") %>%
#   filter(!str_detect(rates, 'rates'))

ggplot(df_dmgs, aes(rates, future_discounted_dmg)) + geom_point()
```

```{r}
.001+(2*.01)
```

